# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-tailscale
  description: '## Usage  **Stack Level**: Regional  Use this in the catalog or use these variables to overwrite the catalog values'
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
